### ISSUE TITLE
[Question] How many users can peerflix-server handle?

### ISSUE THREAD

**Issue by Ma-x** [asapach/peerflix-server#115]
Hi all, first sorry for my english, maybe it's a noob question but i would like to know if anyone had how many users peerflix can handle withouth crashing? Streaming the same torrent? etc..

The point is to know what are the best / recommended server requirements to handle 10,000 request from the same stream, at the same time. And your experience running a public peerflix-server.

Thank you all,

**Comment by asapach** [comment]
It's definitely not designed for scale. I don't think you can get more than 10 users to stream comfortably.

**Comment by Ma-x** [comment]
What is the first problem that comes to your mind when serving more than 10 users? The only limitations that i see is Ram, HDD, Bandwith.. 
Can you explain more? 

Thanks for your quickly answer @asapach .

**Comment by asapach** [comment]
Actually the first limit you will run into is CPU, because it's single-threaded. Every peer and client require a certain amount of CPU resources to keep them happy, and once it's exhausted everything becomes sluggish. It's less of a problem when the torrent is fully downloaded, because the most expensive part is over.
Slow HDD can be a bottleneck, as well as limited IOPS on a virtual server.
You can run into the default V8 limit of ~1.6GB RAM that Node has if CPU or HDD don't keep up.
Bandwidth is a constant issue, regardless of how many users you have.
