### ISSUE TITLE
Missing ffmpeg in docker image

### ISSUE THREAD

**Issue by pryg-skok** [asapach/peerflix-server#122]
Hi,
FFmpeg is missing in Docker image, so query params like ffmpeg=remux is not working here.

**Comment by asapach** [comment]
Yeah, it's an experimental feature, so I didn't think it would make sense to add it to Dockerfile. You can try adding it yourself by following these instructions: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#ffmpeg-and-ffprobe
If that works out, a PR is welcome.

**Comment by pryg-skok** [comment]
I've created simple PR.

Also it's not clear of how to permanently store torrents.json file from container.
And for now I've solved with couple lines in dockerfile:
```
RUN mkdir -p  /home/app/.config/peerflix-server && \
    echo "[]" > /home/app/.config/peerflix-server/torrents.json
```

And container starts  with option:
`-v /path/to/torrents.json:/home/app/.config/peerflix-server/torrents.json`

but maybe there is a better way? Maybe it can be configureable?

**Comment by asapach** [comment]
Thanks.

I think it would be better to mount `/home/app/.config/peerflix-server` folder, because it can also have [`config.json`](https://github.com/asapach/peerflix-server#configuration) in it:
```
RUN mkdir -p  /home/app/.config/peerflix-server
```
```
 -v /path/to/config:/home/app/.config/peerflix-server
```
You can send a PR for [`Docker.md`](https://github.com/asapach/peerflix-server/blob/master/Docker.md) if you want.

How do you suggest making it more configurable?
