### ISSUE TITLE
Documentation sparse

### ISSUE THREAD

**Issue by Spass1966** [asapach/peerflix-server#167]
How is this different from WebTorrent? Can I use this to embed a video on my self hosted website? Is this the best solution for p2p video streaming? Why was the last release 4 years ago?

**Comment by asapach** [comment]
* WebTorrent is primarily meant to run [in the browser](https://webtorrent.io/faq), whereas peerflix-server simply has a browser interface and a REST api, which allow to access torrents via web
* I would not recommend using it at high scale, because all the web traffic goes through a single node, unless you know what you're doing and have the infrastructure to scale
* The [latest release](https://github.com/asapach/peerflix-server/releases) was in September 2018.
