### ISSUE TITLE
[Help] about starting dev in php :)

### ISSUE THREAD

**Issue by yas9999** [asapach/peerflix-server#56]
Hello,
first thank you so much for this awesome application ♥.
i have some question:
- there is a documentation or ability to create a PHP code that control all features,
something like upload file & get result.
- there is any option to disable store files in disk & use instead stream option (that mean nothing will be stored in server side)
-i have Ubuntu 14.04: in ~/.config/peerflix-server/torrents.json when i put option that mentioned here https://github.com/mafintosh/torrent-stream#full-api 
i get error : Undefined 2 please check this http://i.imgur.com/raReft7.png
PS: i had found in this config file : ["c1bb97836be45ef02e24bdf7bd4e666fd37db8aa"]
i guess it's not the right config.json

Best regards,

**Comment by asapach** [comment]
* You can use the [REST API](https://github.com/asapach/peerflix-server/blob/master/REST.md) to control most of the features.
* I would argue that storage is cheap and by not storing the files you hurt the torrent community, because you will not be able to seed. You can try using [tmpfs](https://www.howtoforge.com/storing-files-directories-in-memory-with-tmpfs) if you have enough memory.

Did you mean `~/.config/peerflix-server/config.json`? You can't really pass the `storage` option in JSON, because it requires an object reference, so it's currently unsupported in peerflix-server.

**Comment by yas9999** [comment]
Thank you, i still have a problem X is stopped when i click on X to close a torrent also some times when i add new magnet link please check image :
![image](https://cloud.githubusercontent.com/assets/5939771/10770876/8472e43a-7ce5-11e5-8527-23d2a42cb8ca.png)

for config.json or else i can't change the directory to store files ?

**Comment by asapach** [comment]
So it just randomly gets killed? How much memory do you have on that machine? In my experience you need at least 512MB or better yet 1GB.

To change the path just save this as `~/.config/peerflix-server/config.json`:

```js
{
  "tmp": "/your/path/here"
}
```

**Comment by yas9999** [comment]
Thank you so much !
i guess it's a memory problem i have only 512 MB,so i will try in dedicated server with 24 GB of ram,
i noticed when i added 2 magnet link with more than 1 GB file-size each i get the problem "Killed"

best regards

**Comment by asapach** [comment]
24 GB is probably overkill. 4 GB should be enough for most scenarios.

[M3U](https://en.wikipedia.org/wiki/M3U) is a file format supported by some media players (e.g. VLC) that allows to play the whole folder at once (e.g. if you have an album or a TV series season).

**Comment by yas9999** [comment]
got it :), thank you so much for help
