### ISSUE TITLE
unable to stream flv and mkv extension types

### ISSUE THREAD

**Issue by piscessignature** [asapach/peerflix-server#58]
I am unable to stream  flv and mkv extension types in my browser.

**Comment by Porco-Rosso** [comment]
If I am not mistaken Mkvs won't work because the start and the end of the file needs to be downloaded for it to work. I'm not sure why it works in VLC though..
Does it work in VLC for you?

If ffmpeg is installed you can add  `?ffmpeg=remux` to the end of your url

See here for more info:
https://github.com/asapach/peerflix-server/issues/19

**Comment by asapach** [comment]
Browsers have varying support for different formats: https://en.wikipedia.org/wiki/HTML5_video#Browser_support. Neither MKV, nor FLV is one of them. As @Porco-Rosso mentioned you can try transcoding to WebM if you want to view it in the browser, or you can install a browser plugin (e.g. VLC has one for Firefox). Alternatively you can just copy the video URL and paste it into a video player of your choice, e.g. press Ctrl+N in VLC.

**Comment by asapach** [comment]
Also see #51

**Comment by ZeoNish** [comment]
`<video src="{{ file.link }}" type='video/x-matroska; codecs="theora, vorbis"' autoplay controls onerror="failed(event)" ></video>`
