### ISSUE TITLE
how to store file on mega or any other cloud storage 

### ISSUE THREAD

**Issue by buziyborni** [asapach/peerflix-server#69]
this is a nice project but i will like to know if possible i can store all downloaded file on mega since it give free 50gb of disk space

**Comment by asapach** [comment]
I don't think it's a good idea, since you'd want the torrent storage to be as fast as possible - ideally an SSD - whereas downloading/uploading to a cloud storage will introduce a lot of latency.
The only way to make it work is to upload the files after download is complete, but there are currently no hooks that would allow this.
Anyway, you can try something like this: https://github.com/matteoserva/MegaFuse
or this: https://megatools.megous.com/

**Comment by buziyborni** [comment]
thanks for the quick reply i was testing the app but it seem like after the download completed the progress bar still show up how to do i make it vanish after download completed

**Comment by AnasQiblawi** [comment]
I think this might be very helpful 
https://www.filestack.com
http://go4up.com
